# Display name in dropdown menu
DisplayName: "Multi Task"

# maximum concurrent running tasks : 1-n
# the value should be less than (at most equal to) the number of logical processors
MaxParallelTasks: 8

# the screenshots should also be scanned inverted : true | false
UseInvertedImages: true

# Scan area to analyze Alliance List screenshots
# Rectangle "X1, Y1, X2, Y2"
AllianceListAnalyzerRect: "3535, 200, 3735, 2015"

# Alliance List boundary points
# BoundaryPoints "X1, X2, X3, X4"
AllianceListBP: "245, 625, 3535, 3800"

# Scan area to analyze the Event List screenshots
# Rectangle "X1, Y1, X2, Y2"
EventListAnalyzerRect: "3600, 225, 3800, 2015"

# Event List boundary points
# BoundaryPoints "X1, X2, X3, X4"
EventListBP: "420, 1000, 3450, 3830"
  
# Scan area to analyze the type (alliance or event) of the screenshot
# Rectangle "X1, Y1, X2, Y2"
RectSsTypeAnalyzer: "160, 20, 430, 80"
  
# Limits and colors (ARGB hex value) for column 'Level'
# "min, max, color"
AccuracyLevelBrushLimits:
- "0, 0.1, #ffd44545"
- "0.101, 0.25, #ffff7545"
- "0.251, 0.5, #fffff156"

# Limits and colors (ARGB hex value) for column 'Score'
# "min, max, color"
AccuracyScoreBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"
  
# Limits and colors (ARGB hex value) for column 'Power'
# "min, max, color"
AccuracyPowerBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"

# should a header be output when copying the data: true | false
UseCopiedDataHeader: true

# the header that is output when copying the data
CopiedDataHeader: "Name\tLevel\tPower\tScore\tPowerRanking\tEventRanking"

# Format for the copied data
# possible field names: Name, Level, Power, Score, PowerRanking, EventRanking
# Field names must be between <>, e.g. <Name>
CopiedDataFormat: "<Name>\t<Level>\t<Power>\t<Score>\t<PowerRanking>\t<EventRanking>"