# Anzeigename im DropDown Menü
xDisplayName: "Multi Task"

# maximal gleichzeitig laufende Aufgaben : 1-n
# der Wert sollte kleiner (maximal gleich) sein als die Anzahl der logischen Prozessoren
MaxParallelTasks: 8

# sollen die Screenshots zusätzlich invertiert gescannt werden : true | false
UseInvertedImages: true

# Event List Boundary Points
# BoundaryPoints "X1, X2, X3, X4"
AllianceListBP: "245, 625, 3535, 3800"

# Alliance List Boundary Points
# BoundaryPoints "X1, X2, X3, X4"
EventListBP: "420, 600, 3450, 3830"

# Scanbereich zum analysieren der Alliance List Screenshots
# Rectangle "X1, Y1, X2, Y2"
AllianceListAnalyzerRect: "3535, 210, 3650, 2015"

# Scanbereich zum analysieren der Event Score Positionen
# Rectangle "X1, Y1, X2, Y2"
EventListAnalyzerRect: "3700, 240, 3800, 2000"
  
# Scanbereich zum analysieren der Art (Allianz oder Event) des Screenshots
# Rectangle "X1, Y1, X2, Y2"
RectSsTypeAnalyzer: "160, 20, 430, 80"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Level'
# "Min, Max, Color"
AccuracyLevelBrushLimits:
- "0, 0.1, #ffd44545"
- "0.101, 0.25, #ffff7545"
- "0.251, 0.5, #fffff156"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Score'
# "Min, Max, Color"
AccuracyScoreBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Power'
# "Min, Max, Color"
AccuracyPowerBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"