# Anzeigename im DropDown Menü
DisplayName: "Multi Task ohne InvImg"

# Scanbereich für den Spielernamen in der Eventübersicht
RectEventNames:
  Start:
    X: 420
    Y: 240
  End:
    X: 1000
    Y: 2000

# Scanbereich für die Punktzahl in der Eventübersicht
RectEventScores:
  Start:
    X: 3450
    Y: 240
  End:
    X: 3830
    Y: 2000

# Scanbereich für den Spielernamen in der Allianzübersicht
RectAllianceNames:
  Start:
    X: 245
    Y: 210
  End:
    X: 625
    Y: 2015

# Scanbereich für Power in der Allianzübersicht
RectAlliancePower:
  Start:
    X: 3535
    Y: 210
  End:
    X: 3800
    Y: 2015
  
# Scanbereich zum analysieren der Art (Allianz oder Event) des Screenshots
RectSsTypeAnalyzer:
  Start:
    X: 160
    Y: 20
  End:
    X: 430
    Y: 80

# maximal gleichzeitig laufende Aufgaben : 1-n
# der Wert sollte kleiner (maximal gleich) sein als die Anzahl der logischen Prozessoren
MaxParallelTasks: 8

# sollen die Screenshots zusätzlich invertiert gescannt werden : true | false
UseInvertedImages: false

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Level'
AccuracyLevelBrushLimits:
- Min: 0
  Max: 0.1
  Brush: "#ffd44545"
- Min: 0.101
  Max: 0.25
  Brush: "#ffff7545"
- Min: 0.251
  Max: 0.5
  Brush: "#fffff156"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Score'
AccuracyScoreBrushLimits:
- Min: 0
  Max: 0.333
  Brush: "#ffd44545"
- Min: 0.334
  Max: 0.5
  Brush: "#ffff7545"
- Min: 0.501
  Max: 0.8
  Brush: "#fffff156"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Power'
AccuracyPowerBrushLimits:
- Min: 0
  Max: 0.333
  Brush: "#ffd44545"
- Min: 0.334
  Max: 0.5
  Brush: "#ffff7545"
- Min: 0.501
  Max: 0.8
  Brush: "#fffff156"