# Anzeigename im DropDown Menü
DisplayName: "Test"

# maximal gleichzeitig laufende Aufgaben : 1-n
# der Wert sollte kleiner (maximal gleich) sein als die Anzahl der logischen Prozessoren
MaxParallelTasks: 8

# sollen die Screenshots zusätzlich invertiert gescannt werden : true | false
UseInvertedImages: true

# Scanbereich für den Spielernamen in der Eventübersicht
# Rectangle "X1, Y1, X2, Y2"
RectEventNames: "420, 240, 1000, 2000"

# Scanbereich für die Punktzahl in der Eventübersicht
# Rectangle "X1, Y1, X2, Y2"
RectEventScores: "3450, 240, 3830, 2000"

# Scanbereich für den Spielernamen in der Allianzübersicht
# Rectangle "X1, Y1, X2, Y2"
RectAllianceNames: "245, 210, 625, 2015"

# Scanbereich für Power in der Allianzübersicht
# Rectangle "X1, Y1, X2, Y2"
RectAlliancePower: "3535, 210, 3800, 2015"
  
# Scanbereich zum analysieren der Art (Allianz oder Event) des Screenshots
# Rectangle "X1, Y1, X2, Y2"
RectSsTypeAnalyzer: "160, 20, 430, 80"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Level'
# "Min, Max, Color"
AccuracyLevelBrushLimits:
- "0, 0.1, #ffd44545"
- "0.101, 0.25, #ffff7545"
- "0.251, 0.5, #fffff156"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Score'
# "Min, Max, Color"
AccuracyScoreBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Power'
# "Min, Max, Color"
AccuracyPowerBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"