# Anzeigename im DropDown Menü
DisplayName: "Test Hase"

# maximal gleichzeitig laufende Aufgaben : 1-n
# der Wert sollte kleiner (maximal gleich) sein als die Anzahl der logischen Prozessoren
MaxParallelTasks: 6

# sollen die Screenshots zusätzlich invertiert gescannt werden : true | false
UseInvertedImages: true

# Scanbereich zum analysieren der Alliance List Screenshots
# Rectangle "X1, Y1, X2, Y2"
AllianceListAnalyzerRect: "1755, 130, 1855, 1040"

# Alliance List Boundary Points
# BoundaryPoints "X1, X2, X3, X4"
AllianceListBP: "130, 360, 1755, 1900"

# Scanbereich zum analysieren der Event List Screenshots
# Rectangle "X1, Y1, X2, Y2"
EventListAnalyzerRect: "1810, 145, 1910, 1040"

# Event List Boundary Points
# BoundaryPoints "X1, X2, X3, X4"
EventListBP: "225, 600, 1700, 1910"

# Scanbereich zum analysieren der Art (Allianz oder Event) des Screenshots
# Rectangle "X1, Y1, X2, Y2"
RectSsTypeAnalyzer: "80, 30, 240, 70"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Level'
# "Min, Max, Color"
AccuracyLevelBrushLimits:
- "0, 0.1, #ffd44545"
- "0.101, 0.25, #ffff7545"
- "0.251, 0.5, #fffff156"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Score'
# "Min, Max, Color"
AccuracyScoreBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Power'
# "Min, Max, Color"
AccuracyPowerBrushLimits:
- "0, 0.333, #ffd44545"
- "0.334, 0.5, #ffff7545"
- "0.501, 0.8, #fffff156"