# Scanbereich für den Spielernamen in der Eventübersicht
RectEventNames:
  X: 420
  Y: 240
  Width: 580
  Height: 1760

# Scanbereich für die Punktzahl in der Eventübersicht
RectEventScores:
  X: 3450
  Y: 240
  Width: 380
  Height: 1760

# Scanbereich für den Spielernamen in der Allianzübersicht
RectAllianceNames:
  X: 245
  Y: 210
  Width: 380
  Height: 1805

# Scanbereich für Power in der Allianzübersicht
RectAlliancePower:
  X: 3535
  Y: 210
  Width: 265
  Height: 1805

# Scanbereich zum analysieren der Art (Allianz oder Event) des Screenshots
RectSsTypeAnalyzer:
  X: 160
  Y: 20
  Width: 270
  Height: 60

# maximal gleichzeitig laufende Aufgaben : 1-n
# der Wert sollte kleiner (maximal gleich) sein als die Anzahl der logischen Prozessoren
MaxParallelTasks: 8

# sollen die Screenshots zusätzlich invertiert gescannt werden : true | false
UseInvertedImages: true

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Level'
AccuracyLevelBrushLimits:
- Min: 0
  Max: 0.1
  Brush: "#ffd44545"
- Min: 0.101
  Max: 0.25
  Brush: "#ffff7545"
- Min: 0.251
  Max: 0.5
  Brush: "#fffff156"

# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Score'
AccuracyScoreBrushLimits:
- Min: 0
  Max: 0.333
  Brush: "#ffd44545"
- Min: 0.334
  Max: 0.5
  Brush: "#ffff7545"
- Min: 0.501
  Max: 0.8
  Brush: "#fffff156"
  
# Grenzwerte und Farben (ARGB Hex Wert) für die Spalte 'Power'
AccuracyPowerBrushLimits:
- Min: 0
  Max: 0.333
  Brush: "#ffd44545"
- Min: 0.334
  Max: 0.5
  Brush: "#ffff7545"
- Min: 0.501
  Max: 0.8
  Brush: "#fffff156"